### ISSUE TITLE
Timer throws unlimited "finished" messages

### ISSUE THREAD

**Issue by Nergy101** [kodyVS/Discord-Bot-Development#20]
**Describe the bug**
The bot keeps throwing "Time's up!" when timer finishes.

**To Reproduce**
1. into discord: .timer 1
2. Let it finish
3. Witness Time's Up!-terror

**Expected behavior**
It should just display the Times Up! once

**Desktop:**
 - OS: Linux Ubuntu
 - Version Bionic beaver

**Comment by Destaq** [comment]
@Nergy101 This is fixed in the pull request I have. It was due to the fact that we never decremented the `time` variable once it reached zero. I will close this issue once the pull requested is merged.

**Comment by Destaq** [comment]
Currently review in progress:
https://github.com/kodyVS/Discord-Bot-Development/pull/19
